### ISSUE TITLE
Wrath of the Righteous?

### ISSUE THREAD

**Issue by SpinazFou** [deidril/pf1-pdf-en-import#1]
Me and my group are planning on starting WotR and the GM suggests we use Fantasy Grounds instead. Do you believe it would be possible to use Foundry? I try to turn them over PF2e and Foundry, and it seems the first i can achieve would be to turn them over to Foundry PF1 and then try for PF2e

**Comment by deidril** [comment]
Hi, the module doesn't support AP like WotR at the moment, so if you want instant play without setting up things, Fantasy Grounds maybe great, especially if you don't mind buying all the needed stuff. PDF import module is like someone make an import a given way , using content from a pdf, and the module is able to replicate it if you provide the pdf. Therefore it means someone will have to spend some weeks to configure an import for PF2E WotR. At this time nobody did it.
